### ISSUE TITLE
Renaming BaseEnum to AbstractEnum

### ISSUE THREAD

**Issue by Soullivaneuh** [greg0ire/enum#12]
Should be done if you want to follow Symfony standard.

I can provide a BC PR if you want to.

**Comment by greg0ire** [comment]
Ok for this because it is inherently better IMO, but I don't conclude I especially want to follow the Symfony standard.

**Comment by Soullivaneuh** [comment]
This is why I said:

> if you want to follow Symfony standard

;-)
