### ISSUE TITLE
Relocate Twig label() method in a service?

### ISSUE THREAD

**Issue by laurent-bientz** [greg0ire/enum#137]
Hello @greg0ire 

Why not relocate the code of Twig `label()` method (`enum_label` filter) in a service and simply inject the service in your Twig Extension?

It could be useful if we want to display the "human" value (stored in the translations) in other services/controllers that are not using Twig rendering (e.g. flash messages).

What do you think?

Thanks for this great bundle!
Cheers

**Comment by greg0ire** [comment]
I think it would make sense :)

Were you planning to send a PR?

**Comment by laurent-bientz** [comment]
I'm glad you're ok with that, I will give it a try this week-end or monday ;)
