### ISSUE TITLE
Bump doctrine/inflector?

### ISSUE THREAD

**Issue by laurent-bientz** [greg0ire/enum#142]
Hey @greg0ire,

I got this deprecation notice with a fresh install:

```
User Deprecated: The "Doctrine\Common\Inflector\Inflector::tableize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.
```

According to composer.json, Inflector targets `"^1.0"`, could we upgrade to `"^1.4 || ^2.0"`? 

Thanks in advance!

**Comment by greg0ire** [comment]
Sure! Done.

**Comment by laurent-bientz** [comment]
Thanks sir! :wave:
