### ISSUE TITLE
AbstractEnum test coverage missing

### ISSUE THREAD

**Issue by Soullivaneuh** [greg0ire/enum#38]
![image](https://cloud.githubusercontent.com/assets/1698357/16263459/bfafa826-3874-11e6-8c8b-e13c6af3f8bf.png)

This line is never covered.

BTW, do you know why it's here? The `getEnumTypes` seems to always return an array...

**Comment by greg0ire** [comment]
This was introduced in 017f0e7a . @roukmoute , can you help ?

**Comment by greg0ire** [comment]
IMO it allows to return a single value from `getEnumTypes` when overriding it, for simplicity's sake, but this is not very good because there is an `s` at "types". Should be deprecated and dropped IMO.

**Comment by Soullivaneuh** [comment]
Agree. And when you library will be PHP7 only, you can add an `array` strict return type.

**Comment by Soullivaneuh** [comment]
@greg0ire Do you want to apply https://github.com/greg0ire/enum/issues/38#issuecomment-227705612?

**Comment by greg0ire** [comment]
> @greg0ire Do you want to apply #38 (comment)?

Yes I want to. Did not have time unfortunately. Would you wish me to do it before the release?
