### ISSUE TITLE
Get key from value

### ISSUE THREAD

**Issue by roukmoute** [greg0ire/enum#66]
Is it possible to add a new method to return the key according to a value ?

**Comment by greg0ire** [comment]
Depends. Do you have a good use case that shows this would indeed be useful?

**Comment by roukmoute** [comment]
This is only suggestion.
But yes I have a concrete example when constants name are more expressive than values.
With Symfony, on service, I prefer use constant name than value.
This is an example:
```php
<?php

namespace Model\Constant;

use Greg0ire\Enum\AbstractEnum;

final class KeyConsts extends AbstractEnum
{
    const CANCEL      = "\xEE\x80\x81";
    const HELP        = "\xEE\x80\x82";
    const BACKSPACE   = "\xEE\x80\x83";
}
```

With a context, we can receive the value but it's more comfortable to have a condition by name.

So I must do this things:
```php
public function getKeyFromValue($value)
{
    foreach (KeyConsts::getConstants() as $key => $item) {
        if ($value === $item) {
            return $key;
        }
    }

    return null;
}
```

But it is possible to do this with a map.
So why not add a `map()` method like [ArrayCollection](https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/ArrayCollection.php#L305)?

**Comment by greg0ire** [comment]
Ok, I can see how this could indeed be useful. I would prefer getKeyFromValue to map b/c this is already spécialisés, more than a collection is, and I'd like to keep the interface of an enumeration small and focused. Go ahead and make a PR if you want :) if you do, use exceptions instead of returning null. Also what if two keys give the same value?

**Comment by roukmoute** [comment]
We could add a second argument to stop propagation and return immediately the value.

Or second choice always do all the array and return always an array.

**Comment by greg0ire** [comment]
Or third throw an exception, or fourth just return the first one. Or fifth return array only when needed. This gets complicated... I'd say use solution 1, by default assume there is one key, otherwise return an array.

**Comment by greg0ire** [comment]
See https://github.com/greg0ire/enum/releases/tag/v3.2.0 :)
