### ISSUE TITLE
Dependency injection fail when the translator is disabled

### ISSUE THREAD

**Issue by Soullivaneuh** [greg0ire/enum#89]
On a classic symfony project with the following configuration:

```yaml
framework:
  translator:
    enabled: false
```

You will get the following error:

```
(1/1) ServiceNotFoundExceptionThe
service "greg0ire_enum.twig.extension.enum" has a dependency on a non-existent service "translator.default".
```

This part must be changed: https://github.com/greg0ire/enum/blob/ee59255a89e3e43f06bb232d73eef7b02afa7f75/src/Bridge/Symfony/DependencyInjection/Greg0ireEnumExtension.php#L27-L30

Checking if the translator class is not reliable, we have to check if the definition exists and/or is enabled.

**Comment by greg0ire** [comment]
Just checking if the definition exists should be enough IMO
